version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    restart: always
    container_name: 'tie_server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    links:
      - db:postgres
    ports:
      - "8081:8081"

  web:
    depends_on:
      - server
    container_name: 'tie_web'
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ~/data/nginx/logs:/var/log/nginx
    ports:
      - "8080:8080"